spring:
  profiles:
    active: local
  application:
    name: product
  data:
    mongodb:
      uri: mongodb://localhost:27017/sotti-produc

app:
  admin-api-key: ${ADMIN_API_KEY:}

http:
  timeout:
    default: 30000